// Hide console window on Windows in release mode
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::Deserialize;
use std::env;
use std::fs::{self, File};
use std::io::{self, Read};
use std::path::PathBuf;
use std::process::Command;

/// Unique binary marker (not a string) to avoid false positives in the binary
const PORTABLE_MARKER: &[u8] = &[0xDE, 0xAD, 0xBE, 0xEF, 0x45, 0x4D, 0x55, 0x46, 0x4F, 0x52, 0x47, 0x45, 0x56, 0x32];

// Include the config generated by build.rs
include!(concat!(env!("OUT_DIR"), "/config_gen.rs"));

#[derive(Deserialize)]
#[allow(dead_code)]
struct LaunchConfig {
    emulator_path: PathBuf,
    rom_path: PathBuf,
    #[allow(dead_code)]
    bios_path: Option<PathBuf>,
    args: Vec<String>,
    working_dir: Option<PathBuf>,
    env_vars: Vec<(String, String)>,
}

#[derive(Deserialize)]
struct PortableConfig {
    game_name: String,
    emulator_filename: String,
    rom_filename: String,
    config_dir: String,
    fullscreen: bool,
}

fn main() {
    // Check if we're in portable mode by looking for the marker in ourselves
    let exe_path = env::current_exe().expect("Failed to get current exe path");
    
    if let Some(portable_config) = check_portable_mode(&exe_path) {
        run_portable_mode(exe_path, portable_config);
    } else {
        run_launcher_mode();
    }
}

/// Check if the executable contains embedded portable data
fn check_portable_mode(exe_path: &PathBuf) -> Option<PortableConfig> {
    let mut file = File::open(exe_path).ok()?;
    
    // We only need to read the beginning of the file to find the marker
    // because the marker is appended directly after the stub binary.
    // 10MB is more than enough for any stub binary.
    let mut buffer = vec![0u8; 10 * 1024 * 1024]; 
    let bytes_read = file.read(&mut buffer).ok()?;
    buffer.truncate(bytes_read);
    
    // Search for marker starting from the END of the buffer to find the REAL one
    if let Some(pos) = buffer.windows(PORTABLE_MARKER.len()).rposition(|window| window == PORTABLE_MARKER) {
        // Marker found! Read the config JSON that follows
        let config_start = pos + PORTABLE_MARKER.len();
        
        // Read 4 bytes for config length
        if buffer.len() < config_start + 4 {
            return None;
        }
        let config_len = u32::from_le_bytes([
            buffer[config_start],
            buffer[config_start + 1],
            buffer[config_start + 2],
            buffer[config_start + 3],
        ]) as usize;
        
        let config_data_start = config_start + 4;
        if buffer.len() < config_data_start + config_len {
            return None;
        }
        
        let config_json = &buffer[config_data_start..config_data_start + config_len];
        serde_json::from_slice::<PortableConfig>(config_json).ok()
    } else {
        None
    }
}

/// Find subsequence in buffer

/// Run in portable mode - extract and launch
fn run_portable_mode(exe_path: PathBuf, config: PortableConfig) {
    // Determine cache directory
    let cache_base = dirs::cache_dir()
        .unwrap_or_else(|| PathBuf::from("/tmp"))
        .join("emuforge");
    let target_dir = cache_base.join(&config.game_name);
    
    // Check if already extracted
    let marker_file = target_dir.join(".emuforge_extracted");
    let needs_extraction = !marker_file.exists();
    
    if needs_extraction {
        eprintln!("🎮 Préparation du jeu: {}...", config.game_name);
        eprintln!("📁 Dossier de données: {:?}", target_dir);
        
        // Create cache directory
        fs::create_dir_all(&target_dir).expect("Failed to create cache directory");
        
        // Extract the embedded zip archive
        if let Err(e) = extract_embedded_archive(&exe_path, &target_dir) {
            eprintln!("❌ Erreur d'extraction: {}", e);
            std::process::exit(1);
        }
        
        // Create marker file
        let _ = File::create(&marker_file);
        eprintln!("✅ Extraction terminée !");
    } else {
        // Even if already extracted, we RE-EXTRACT ONLY THE CONFIG to ensure resolution settings
        // are updated if the user changed them.
        let _ = extract_embedded_archive(&exe_path, &target_dir);
    }
    
    // Build paths to extracted files
    let emulator_path = target_dir.join(&config.emulator_filename);
    let rom_path = target_dir.join(&config.rom_filename);
    let config_path = target_dir.join(&config.config_dir);
    
    // Make emulator executable (Linux)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(metadata) = fs::metadata(&emulator_path) {
            let mut perms = metadata.permissions();
            perms.set_mode(0o755);
            let _ = fs::set_permissions(&emulator_path, perms);
        }
    }
    
    // Launch the emulator
    let mut cmd = Command::new(&emulator_path);
    
    // CRITICAL: Set HOME to the config directory to isolate the emulator
    // This replicates the logic in our wrapper script and fixes the DuckStation error.
    cmd.env("HOME", &config_path);
    cmd.env("QT_QPA_PLATFORM", "xcb");
    
    // DuckStation syntax: [flags] -- <file>
    if config.fullscreen {
        cmd.arg("-fullscreen");
    }
    cmd.arg("--");
    cmd.arg(&rom_path);
    
    let mut child = cmd.spawn().expect("Failed to launch emulator");
    let _ = child.wait();
}

/// Extract the embedded ZIP archive from the executable
fn extract_embedded_archive(exe_path: &PathBuf, target_dir: &PathBuf) -> io::Result<()> {
    use std::io::{Seek, SeekFrom};
    let mut file = File::open(exe_path)?;
    
    // Search for the marker in the first 10MB
    let mut header = vec![0u8; 10 * 1024 * 1024];
    let n = file.read(&mut header)?;
    header.truncate(n);
    
    // Search for marker starting from the END of the buffer
    if let Some(pos) = header.windows(PORTABLE_MARKER.len()).rposition(|window| window == PORTABLE_MARKER) {
        let config_start = pos + PORTABLE_MARKER.len();
        
        // Read config length (4 bytes)
        let config_len = u32::from_le_bytes([
            header[config_start],
            header[config_start + 1],
            header[config_start + 2],
            header[config_start + 3],
        ]) as usize;
        
        let zip_start = (config_start + 4 + config_len) as u64;
        
        // Seek to the start of ZIP data
        file.seek(SeekFrom::Start(zip_start))?;
        
        // Write ZIP to temporary file by streaming
        let zip_temp_path = target_dir.join("temp_data.zip");
        let mut temp_file = File::create(&zip_temp_path)?;
        io::copy(&mut file, &mut temp_file)?;
        
        // Extract ZIP
        let zip_read_file = File::open(&zip_temp_path)?;
        let mut archive = zip::ZipArchive::new(zip_read_file)?;
        
        for i in 0..archive.len() {
            let mut out_file = archive.by_index(i)?;
            let outpath = match out_file.enclosed_name() {
                Some(path) => target_dir.join(path),
                None => continue,
            };
            
            if out_file.name().ends_with('/') {
                fs::create_dir_all(&outpath)?;
            } else {
                if let Some(p) = outpath.parent() {
                    if !p.exists() {
                        fs::create_dir_all(&p)?;
                    }
                }
                let mut outfile = File::create(&outpath)?;
                io::copy(&mut out_file, &mut outfile)?;
                
                // Set executable permissions if needed (Linux)
                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    if let Some(mode) = out_file.unix_mode() {
                        fs::set_permissions(&outpath, fs::Permissions::from_mode(mode)).ok();
                    }
                }
            }
        }
        
        // Remove temporary ZIP
        let _ = fs::remove_file(&zip_temp_path);
        Ok(())
    } else {
        Err(io::Error::new(io::ErrorKind::NotFound, "Marker not found"))
    }
}

/// Run in launcher mode - use embedded config
fn run_launcher_mode() {
    let config: LaunchConfig = serde_json::from_str(CONFIG_JSON)
        .expect("Failed to parse embedded config");

    let mut cmd = Command::new(&config.emulator_path);
    
    if let Some(working_dir) = config.working_dir {
        cmd.current_dir(working_dir);
    }

    for (key, value) in config.env_vars {
        cmd.env(key, value);
    }

    // Determine if we need DuckStation specific HOME isolation
    let is_duckstation = config.emulator_path.to_string_lossy().to_lowercase().contains("duckstation");
    if is_duckstation {
        // Find if we have a .duckstation_home next to the executable
        if let Ok(exe_path) = env::current_exe() {
            if let Some(exe_dir) = exe_path.parent() {
                let fake_home = exe_dir.join(".duckstation_home");
                if fake_home.exists() {
                    cmd.env("HOME", fake_home);
                    cmd.env("QT_QPA_PLATFORM", "xcb");
                }
            }
        }
    }

    cmd.args(&config.args);
    
    // In launcher mode, if rom_path is not empty, we add it.
    // If it's a wrapper script, rom_path might have been cleared in the UI logic.
    if !config.rom_path.as_os_str().is_empty() {
        cmd.arg(&config.rom_path);
    }

    let mut child = cmd.spawn().expect("Failed to launch emulator");
    let _ = child.wait();
}
